export const initialBlogs = [
  {
    site_id: 1,
    title: "מדריך לקניית רכב חדש ב-2024",
    description: "הכללים והטיפים החשובים לבחירת הרכב המושלם עבורכם.",
    content: `איך לבחור רכב חדש?
    
במדריך זה נסקור את הדגמים החדשים לשנת 2024 ונציג את היתרונות של כל אחד.`,
    image_url:
      "https://images.unsplash.com/photo-1518169640858-dfbb83c2e1c7?q=80&w=2070&auto=format&fit=crop",
    meta_title: "מדריך לקניית רכב חדש ב-2024",
    meta_description: "הטיפים הטובים ביותר לקניית רכב חדש בשנת 2024.",
    slug: "car-buying-guide-2024",
    tags: "רכב חדש,קניית רכב,2024",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "תחזוקת רכב - איך לשמור על הרכב שלכם כמו חדש?",
    description: "כללים בסיסיים לתחזוקת רכב נכונה לאורך זמן.",
    content: `תחזוקת רכב חשובה לא רק לביצועי הרכב אלא גם לשמירה על ערכו.`,
    image_url:
      "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=2070&auto=format&fit=crop",
    meta_title: "תחזוקת רכב - טיפים לשמירה על רכב חדש",
    meta_description: "מדריך לתחזוקת רכב לשמירה על ערכו לאורך זמן.",
    slug: "car-maintenance-tips",
    tags: "תחזוקה,רכב,שמירה",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "5 המכוניות החשמליות הטובות ביותר ב-2024",
    description: "סקירת דגמי הרכב החשמליים המובילים לשנה זו.",
    content: `יתרונות של רכבים חשמליים
הרכבים החשמליים מובילים את המהפכה הירוקה והם גם חסכוניים ואמינים.`,
    image_url:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=2070&auto=format&fit=crop",
    meta_title: "5 המכוניות החשמליות המומלצות ב-2024",
    meta_description: "רשימת דגמי הרכב החשמליים הטובים ביותר לשנה זו.",
    slug: "top-5-electric-cars-2024",
    tags: "רכבים חשמליים,2024,סקירות",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "הבדלים בין מנועי דיזל לבנזין",
    description: "מהם היתרונות והחסרונות של כל אחד מהמנועים?",
    content: `מנועי דיזל ובנזין שונים בביצועים, עלויות התחזוקה, ויעילות הדלק.`,
    image_url:
      "https://images.unsplash.com/photo-1536786761079-a2cd6b381f43?q=80&w=2070&auto=format&fit=crop",
    meta_title: "דיזל או בנזין - מה מתאים לכם?",
    meta_description: "השוואה בין מנועי דיזל ובנזין - יתרונות וחסרונות.",
    slug: "diesel-vs-petrol-engines",
    tags: "מנועים,דיזל,בנזין",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "היסטוריית המותגים הגדולים בעולם הרכב",
    description: "המותגים שכבשו את עולם הרכב לאורך השנים.",
    content: `מותגים מובילים כמו BMW, Toyota ו-Ford שינו את עולם הרכב.`,
    image_url:
      "https://images.unsplash.com/photo-1523986371872-9d3ba2e2f5d6?q=80&w=2070&auto=format&fit=crop",
    meta_title: "המותגים הגדולים בעולם הרכב",
    meta_description: "היסטוריה על המותגים המובילים בתעשיית הרכב.",
    slug: "history-of-top-car-brands",
    tags: "מותגים,רכב,היסטוריה",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "איך לבחור ביטוח רכב?",
    description: "הטיפים החשובים ביותר לבחירת ביטוח רכב שמתאים לכם.",
    content: `ביטוח חובה או מקיף? מה הכי נכון עבורכם?`,
    image_url:
      "https://images.unsplash.com/photo-1511268559334-f9c76e4d8d9d?q=80&w=2070&auto=format&fit=crop",
    meta_title: "בחירת ביטוח רכב",
    meta_description: "מדריך לבחירת ביטוח רכב מושלם עבורכם.",
    slug: "choosing-car-insurance",
    tags: "ביטוח רכב,טיפים,מדריך",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "טיפים לנהיגה חסכונית בדלק",
    description: "איך להפחית את עלויות הדלק שלכם בקלות.",
    content: `נהיגה חסכונית היא לא רק חיסכון בכסף, אלא גם שמירה על הסביבה.`,
    image_url:
      "https://images.unsplash.com/photo-1495435229349-e86db7bfa013?q=80&w=2070&auto=format&fit=crop",
    meta_title: "נהיגה חסכונית - טיפים",
    meta_description: "טיפים לנהיגה חסכונית ולחיסכון בדלק.",
    slug: "fuel-efficient-driving-tips",
    tags: "נהיגה חסכונית,דלק,טיפים",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "5 הטכנולוגיות המתקדמות ביותר בעולם הרכב",
    description: "מהן הטכנולוגיות שמשנות את עולם הרכב?",
    content: `טכנולוגיות כמו רכבים אוטונומיים ורכבים חשמליים מובילים את התחום.`,
    image_url:
      "https://images.unsplash.com/photo-1516117172878-fd2c41f4a759?q=80&w=2070&auto=format&fit=crop",
    meta_title: "טכנולוגיות מתקדמות ברכב",
    meta_description: "הצצה לטכנולוגיות החדשניות ביותר בעולם הרכב.",
    slug: "advanced-car-technologies",
    tags: "טכנולוגיות,רכב,חדשנות",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "איך לבחור צמיגים מתאימים לרכב?",
    description: "המדריך המלא לבחירת צמיגים איכותיים ובטוחים.",
    content: `בחירת צמיגים נכונה יכולה לשפר את בטיחותכם ויעילות הרכב.`,
    image_url:
      "https://images.unsplash.com/photo-1516302350523-fcf219d9b072?q=80&w=2070&auto=format&fit=crop",
    meta_title: "בחירת צמיגים לרכב",
    meta_description: "מדריך לבחירת צמיגים נכונים ובטוחים.",
    slug: "choosing-car-tires",
    tags: "צמיגים,בטיחות,רכב",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "מכוניות קלאסיות - האגדות של עולם הרכב",
    description: "הצצה לדגמי הרכב הקלאסיים שהפכו לאייקונים.",
    content: `מכוניות קלאסיות כמו Porsche 911 ו-Ford Mustang יישארו בזיכרון לעד.`,
    image_url:
      "https://images.unsplash.com/photo-1517159911674-56a5bf1723f5?q=80&w=2070&auto=format&fit=crop",
    meta_title: "מכוניות קלאסיות",
    meta_description: "רשימת המכוניות הקלאסיות שהשפיעו על עולם הרכב.",
    slug: "classic-cars-legends",
    tags: "מכוניות קלאסיות,רכב,היסטוריה",
    status: "Published",
    video_url: null,
    gallery_urls: null,
  },
  {
    site_id: 1,
    title: "איך לבחור רכב חדש ב-2024?",
    description: "כל מה שצריך לדעת לפני רכישת רכב חדש",
    content: `קניית רכב היא אחת ההחלטות הכלכליות החשובות ביותר. 
    במאמר זה נסקור את היתרונות והחסרונות של רכבים היברידיים, חשמליים ודלק.`,
    image_url: "https://images.unsplash.com/photo-1611782286137-6c89c1db65b1",
    meta_title: "מדריך קניית רכב",
    meta_description: "איך לבחור רכב חדש שמתאים בדיוק לצרכים שלך?",
    slug: "buying-car-guide-2024",
    tags: "רכבים, קנייה, טיפים",
    status: "Published",
  },
  {
    site_id: 1,
    title: "טיפים לחיסכון בדלק",
    description: "איך אפשר לחסוך מאות שקלים בחודש בהוצאות על דלק?",
    content: `בין אם אתה נוסע לעבודה או יוצא לטיול, הנה מספר דרכים פשוטות להפחית את צריכת הדלק.`,
    image_url: "https://images.unsplash.com/photo-1610073830470-b7b9d93f3c85",
    meta_title: "איך לחסוך בדלק?",
    meta_description: "הדרכים הטובות ביותר לחסוך בעלויות נסיעה.",
    slug: "fuel-saving-tips",
    tags: "חיסכון, דלק, תחבורה",
    status: "Published",
  },
];
