export const initialSubscribers = [
  {
    site_id: 1,
    email: "subscriber1@example.com",
    name: "יוסי לוי",
    subscription_date: new Date("2024-01-01T10:00:00Z"), // המרה ל- Date
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber2@example.com",
    name: "שרה כהן",
    subscription_date: new Date("2024-01-05T14:30:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber3@example.com",
    name: "איילה רוזנברג",
    subscription_date: new Date("2024-01-10T09:15:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber4@example.com",
    name: "דוד בן חמו",
    subscription_date: new Date("2024-01-12T16:45:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber5@example.com",
    name: "איתי זיו",
    subscription_date: new Date("2024-01-15T11:20:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber6@example.com",
    name: "נועה פרץ",
    subscription_date: new Date("2024-01-18T08:30:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber7@example.com",
    name: "משה דקל",
    subscription_date: new Date("2024-01-20T13:50:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber8@example.com",
    name: "רחל אבגיל",
    subscription_date: new Date("2024-01-22T09:10:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber9@example.com",
    name: "יונתן כהן",
    subscription_date: new Date("2024-01-25T17:30:00Z"),
    status: "Subscribed",
  },
  {
    site_id: 1,
    email: "subscriber10@example.com",
    name: "מיכאל ברגר",
    subscription_date: new Date("2024-01-28T12:00:00Z"),
    status: "Subscribed",
  },
];
