export const initialPages = [
  {
    site_id: 1,
    name: "home",
    title: "ברוכים הבאים לאתר שלנו",
    meta_title: "עמוד הבית - חווה אורגנית",
    meta_description:
      "ברוכים הבאים לעמוד הבית של החווה האורגנית שלנו, הכולל מידע כללי ותמונות.",
    meta_keywords: "חווה, אורגני, משתלה, ירקות",
    description: "עמוד הבית עם מידע על החווה ותמונות.",
  },
  {
    site_id: 1,
    name: "weekly-produce",
    title: "תוצרת שבועית",
    meta_title: "תוצרת אורגנית טרייה - החווה שלנו",
    meta_description:
      "התוצרת השבועית שלנו כוללת מגוון ירקות ופירות אורגניים טריים.",
    meta_keywords: "תוצרת שבועית, ירקות, פירות, אורגני",
    description: "עמוד המציג את התוצרת השבועית הטרייה שלנו.",
  },
  {
    site_id: 1,
    name: "delivery",
    title: "שירות משלוחים",
    meta_title: "משלוחים - החווה שלנו",
    meta_description: "שירות משלוחים מהיר לכל האזור.",
    meta_keywords: "משלוחים, חקלאות, חווה, שירות",
    description: "מידע על שירות המשלוחים וזמני האספקה.",
  },
  {
    site_id: 1,
    name: "contact",
    title: "צור קשר",
    meta_title: "צור קשר - החווה שלנו",
    meta_description: "ניתן ליצור איתנו קשר לגבי הזמנות, שאלות ומידע נוסף.",
    meta_keywords: "צור קשר, תמיכה, שירות לקוחות",
    description: "עמוד יצירת קשר עם פרטי התקשרות.",
  },
  {
    site_id: 1,
    name: "blog",
    title: "הבלוג",
    meta_title: "בלוג - החווה שלנו",
    meta_description: "בלוג עם מאמרים ועדכונים מהחווה.",
    meta_keywords: "בלוג, מאמרים, חקלאות, חווה",
    description: "עמוד הבלוג עם מאמרים ועדכונים מהחווה.",
  },
  {
    site_id: 1,
    name: "about",
    title: "אודות",
    meta_title: "אודות - החווה שלנו",
    meta_description: "מידע על החווה והחזון שלנו.",
    meta_keywords: "אודות, חווה אורגנית, חקלאות",
    description: "עמוד אודות עם מידע על החזון וההיסטוריה של החווה.",
  },
];
