export const initialProducts = [
  {
    site_id: 1,
    name: "שמן מנוע איכותי 5W-30",
    description: "שמן מנוע סינתטי מלא המספק הגנה גבוהה ושיפור ביצועי המנוע.",
    weight: "1 ליטר",
    category: "תחזוקת רכב",
    price: 65,
    image_url:
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=2071&auto=format&fit=crop",
    stock_quantity: 100,
    is_featured: true,
    discount_percentage: 10,
    tags: "תחזוקת רכב,שמן מנוע,5W-30",
    meta_title: "שמן מנוע איכותי 5W-30",
    meta_description: "שמן מנוע סינתטי מלא לשיפור ביצועי הרכב והגנה על המנוע.",
    slug: "engine-oil-5w30",
    additional_images: JSON.stringify([
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=800",
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=600",
    ]),
    video_url: null,
    status: "Active",
  },
  {
    site_id: 1,
    name: "מסנן שמן לרכב",
    description: "מסנן שמן איכותי המתאים למגוון רחב של דגמי רכב.",
    weight: "500 גרם",
    category: "תחזוקת רכב",
    price: 40,
    image_url:
      "https://images.unsplash.com/photo-1612463758848-f15415fc7b44?q=80&w=2071&auto=format&fit=crop",
    stock_quantity: 50,
    is_featured: false,
    discount_percentage: 0,
    tags: "מסנן שמן,תחזוקת רכב",
    meta_title: "מסנן שמן איכותי לרכב",
    meta_description: "מסנן שמן איכותי להגנה ושיפור ביצועי המנוע.",
    slug: "car-oil-filter",
    additional_images: JSON.stringify([]),
    video_url: null,
    status: "Active",
  },
  {
    site_id: 1,
    name: "מטען למצבר 12V",
    description: "מטען איכותי למצברי רכב 12V, מתאים לשימוש ביתי ומקצועי.",
    weight: "2 ק״ג",
    category: "אביזרים",
    price: 120,
    image_url:
      "https://images.unsplash.com/photo-1585600059461-fdc365a7c759?q=80&w=2071&auto=format&fit=crop",
    stock_quantity: 30,
    is_featured: true,
    discount_percentage: 5,
    tags: "מטען מצבר,אביזרים",
    meta_title: "מטען למצבר רכב 12V",
    meta_description: "מטען איכותי למצברים - מתאים לשימוש ביתי ומקצועי.",
    slug: "car-battery-charger-12v",
    additional_images: JSON.stringify([
      "https://images.unsplash.com/photo-1585600059461-fdc365a7c759?q=80&w=800",
    ]),
    video_url: "https://www.youtube.com/watch?v=dummy-video",
    status: "Active",
  },
  {
    site_id: 1,
    name: "שואב אבק לרכב",
    description: "שואב אבק קומפקטי וחזק לניקוי פנים הרכב.",
    weight: "1.2 ק״ג",
    category: "ניקיון רכב",
    price: 150,
    image_url:
      "https://images.unsplash.com/photo-1592878849126-5c9c6ba72b12?q=80&w=2071&auto=format&fit=crop",
    stock_quantity: 25,
    is_featured: false,
    discount_percentage: 0,
    tags: "שואב אבק,ניקיון רכב",
    meta_title: "שואב אבק לרכב - קומפקטי וחזק",
    meta_description: "שואב אבק קל לשימוש ונוח לניקוי פנים הרכב.",
    slug: "car-vacuum-cleaner",
    additional_images: JSON.stringify([]),
    video_url: null,
    status: "Active",
  },
  {
    site_id: 1,
    name: "ערכת חירום לרכב",
    description: "ערכת חירום מלאה הכוללת כבלים להתנעה, פנס וכלי עבודה בסיסיים.",
    weight: "3 ק״ג",
    category: "אביזרים",
    price: 200,
    image_url:
      "https://images.unsplash.com/photo-1541447277276-419160135ebf?q=80&w=2071&auto=format&fit=crop",
    stock_quantity: 15,
    is_featured: true,
    discount_percentage: 20,
    tags: "ערכת חירום,אביזרים",
    meta_title: "ערכת חירום לרכב",
    meta_description: "ערכת חירום חיונית לכל נהג, כוללת כלים ואביזרים.",
    slug: "car-emergency-kit",
    additional_images: JSON.stringify([
      "https://images.unsplash.com/photo-1541447277276-419160135ebf?q=80&w=800",
    ]),
    video_url: null,
    status: "Active",
  },
];
