export const initialSiteInfo = [
  {
    site_name: "שם האתר",
    description: "תיאור",
    address: "כתובת, עיר, מדינה",
    contact_email: "my_email@mail.com",
    phone_number: "972521234567",
    opening_hours: "א-ה, 9:00-17:00",
    meta_title: "כותרת עבור מנועי חיפוש",
    meta_description: "תיאור עבור מנועי חיפוש",
    og_title: "כותרת עבור פייסבוק",
    og_description: "תיאור עבור פייסבוק",
    og_url: "https://www.mywebsite.com",
    og_type: "website",
    facebook_url: "https://www.facebook.com/",
    instagram_url: "https://www.instagram.com/",
    twitter_url: "https://www.twitter.com/",
    youtube_url: "https://www.youtube.com/",
  },
];
