export const initialSiteInfo = [
  {
    site_name: "עולם הרכב",
    description: "האתר המוביל לחדשות, טיפים ומידע על עולם הרכב.",
    address: "רחוב המכוניות, תל אביב, ישראל",
    contact_email: "info@carworld.com",
    phone_number: "972521234567",
    opening_hours: "א-ה, 9:00-18:00",
    meta_title: "עולם הרכב - חדשות וטיפים על רכבים",
    meta_description: "האתר המוביל לחדשות, ביקורות וטיפים על רכבים מכל הסוגים.",
    og_title: "עולם הרכב - כל מה שרציתם לדעת על רכבים",
    og_description:
      "גלו חדשות, ביקורות וטיפים על רכבים באתר המוביל לעולם הרכב.",
    og_url: "https://www.carworld.com",
    og_type: "website",
    facebook_url: "https://www.facebook.com/carworld",
    instagram_url: "https://www.instagram.com/carworld",
    twitter_url: "https://www.twitter.com/carworld",
    youtube_url: "https://www.youtube.com/carworld",
    logo_url: "https://www.carworld.com/images/logo.png",
    favicon_url: "https://www.carworld.com/images/favicon.ico",
    google_analytics_id: "UA-12345678-1",
    facebook_pixel_id: "1234567890",
    default_language: "he",
    supported_languages: "he,en",
    twitter_handle: "@carworld",
    default_image_url: "https://www.carworld.com/images/default.jpg",
  },
];
